# Generated by Django 3.2.3 on 2021-09-25 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image/')),
                ('confidences', models.FloatField()),
                ('result', models.CharField(max_length=10)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
