# Generated by Django 3.2.3 on 2021-11-24 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_image_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
